const API_KEY = 'ft_kiodoa_2f917696298d3baa5ac9f9eb9dcb33200a4275de';
const BASE = 'https://api.kickoffapi.com/api/v1';
const CACHE_VERSION = 'vm2026-kickoffapi-real-v4-no-demo';
const WORLD_CUP_LEAGUE_ID = '1';
const SEASON = '2026';
const navItems = [
  ['overview','⌂','Oversigt'],['matches','▣','Kampe'],['groups','☷','Grupper'],['teams','●','Hold'],['stadiums','◉','Stadions'],['favorites','★','Favoritter'],['settings','⚙','Indstillinger']
];
const state = { view:'overview', fixtures:[], teams:[], standings:[], venues:[], selected:null, detailTab:'fakta', loading:false, error:'', favorites:new Set(JSON.parse(localStorage.getItem('favorites')||'[]')) };
const $ = s => document.querySelector(s);
const esc = v => String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const get = (obj,path,def='') => path.split('.').reduce((o,k)=>o?.[k],obj) ?? def;
function normList(json){ if(Array.isArray(json?.response)) return json.response; if(Array.isArray(json?.data)) return json.data; if(Array.isArray(json?.fixtures)) return json.fixtures; if(Array.isArray(json)) return json; return []; }
function flag(team){return team?.logo || team?.flag || get(team,'team.logo') || ''}
function teamName(t){return t?.name || t?.team?.name || t || 'Ukendt'}
function teamId(t){return t?.id || t?.teamId || t?.team?.id || ''}
function fixtureId(f){return f.id || f.fixtureId || get(f,'fixture.id') || f.fixture_id;}
function dt(f){ const raw=f.date||get(f,'fixture.date')||f.kickoff; if(raw){const d=new Date(raw); if(!isNaN(d)) return d;} const ts=f.timestamp||get(f,'fixture.timestamp'); if(ts){const d=new Date(Number(ts)*1000); if(!isNaN(d)) return d;} return null; }
function dateText(f){const d=dt(f); return d?d.toLocaleString('da-DK',{dateStyle:'medium',timeStyle:'short'}):'Dato ukendt'}
function status(f){return f.statusShort || get(f,'fixture.status.short') || get(f,'fixture.status') || f.status || ''}
function isFinished(f){return ['FT','AET','PEN'].includes(status(f));}
function isStarted(f){return !['NS','TBD','PST','CANC',''].includes(status(f)) || Number.isFinite(Number(f.goalsHome)) || Number.isFinite(Number(f.goalsAway));}
function score(f){ const h = f.goalsHome ?? f.scoreFullHome ?? get(f,'goals.home'); const a = f.goalsAway ?? f.scoreFullAway ?? get(f,'goals.away'); return `${h??'-'} - ${a??'-'}`; }
function scoreParts(f){return {h:f.goalsHome ?? f.scoreFullHome ?? get(f,'goals.home'), a:f.goalsAway ?? f.scoreFullAway ?? get(f,'goals.away')}}
function home(f){return f.homeTeam || get(f,'teams.home') || f.home || {name:'Hjemmehold', logo:''}}
function away(f){return f.awayTeam || get(f,'teams.away') || f.away || {name:'Udehold', logo:''}}
function venueOf(f){return f.venue || get(f,'fixture.venue') || {}}
function deriveTeams(fixtures){const m=new Map(); fixtures.forEach(f=>[home(f),away(f)].forEach(t=>{const id=teamId(t)||teamName(t); if(id&&!m.has(id))m.set(id,{team:t});})); return [...m.values()].sort((a,b)=>teamName(a.team).localeCompare(teamName(b.team),'da'));}
function deriveVenues(fixtures){const m=new Map(); fixtures.forEach(f=>{const v=venueOf(f); const id=v.id||v.name; if(id&&!m.has(id))m.set(id,{venue:v});}); return [...m.values()].sort((a,b)=>(a.venue.name||'').localeCompare(b.venue.name||'','da'));}
async function api(path, params={}, ttl=10*60*1000){
  const url = new URL(BASE + path); Object.entries(params).forEach(([k,v])=>{ if(v!==undefined && v!==null && v!=='') url.searchParams.set(k,v); });
  const key = CACHE_VERSION+':'+url.toString(); const cached = JSON.parse(localStorage.getItem(key)||'null'); if(cached && Date.now()-cached.t < ttl) return cached.data;
  const res = await fetch(url, {headers:{'x-api-key':API_KEY, 'Accept':'application/json'}});
  const available = res.headers.get('X-Requests-Available-Minute') || res.headers.get('x-ratelimit-remaining'); if($('#quotaNote') && available) $('#quotaNote').textContent = `API-kald tilbage: ${available}`;
  const text = await res.text(); let data; try{data=JSON.parse(text)}catch{data={raw:text}}
  if(!res.ok) throw new Error(`API-fejl ${res.status}: ${data?.message || data?.error || text.slice(0,120)}`);
  if(data?.errors && Object.keys(data.errors).length) throw new Error('API-fejl: '+JSON.stringify(data.errors));
  localStorage.setItem(key, JSON.stringify({t:Date.now(),data})); return data;
}
function fixtureParams(extra={}){return {league:WORLD_CUP_LEAGUE_ID, season:SEASON, ...extra};}
async function loadCore(force=false){
  if(force){Object.keys(localStorage).filter(k=>k.startsWith(CACHE_VERSION+':')).forEach(k=>localStorage.removeItem(k));}
  state.loading=true; render();
  try{
    const [fx, st] = await Promise.allSettled([api('/fixtures', fixtureParams(), 2*60*1000), api('/standings', fixtureParams(), 30*60*1000)]);
    state.fixtures = fx.status==='fulfilled'?normList(fx.value):[]; state.standings = st.status==='fulfilled'?normList(st.value):[]; state.teams=deriveTeams(state.fixtures); state.venues=deriveVenues(state.fixtures); state.error = fx.status==='rejected'?fx.reason.message:'';
  }catch(e){ state.error=e.message; }
  state.loading=false; render();
}
async function loadDetail(f){
  state.detailTab='fakta'; state.selected={fixture:f, events:null, lineups:null, stats:null, errors:[], loading:true}; render();
  const id=fixtureId(f); const calls=[['events','/fixtures/events',{fixture:id}],['lineups','/fixtures/lineups',{fixture:id}],['stats','/fixtures/statistics',{fixture:id}]];
  await Promise.all(calls.map(async ([k,p,params])=>{try{state.selected[k]=normList(await api(p,params,60*1000));}catch(e){state.selected.errors.push(k+': '+e.message); state.selected[k]=[];}}));
  state.selected.loading=false; render();
}
function setView(v){state.view=v; state.selected=null; render(); if(!state.fixtures.length && v!=='settings') loadCore();}
function renderNav(){const html=navItems.map(([id,ico,label])=>`<button class="${state.view===id?'active':''}" onclick="setView('${id}')"><span>${ico}</span><span>${label}</span></button>`).join(''); $('#sideNav').innerHTML=html; $('#bottomNav').innerHTML=navItems.slice(0,5).map(([id,ico,label])=>`<button class="${state.view===id?'active':''}" onclick="setView('${id}')"><span class="ico">${ico}</span><span>${label}</span></button>`).join('');}
function render(){renderNav(); $('#pageTitle').textContent = state.selected?'Kampinfo':(navItems.find(x=>x[0]===state.view)?.[2]||'VM 2026'); $('#subTitle').textContent = state.selected?'Fakta, opstillinger, statistik og kampforløb':'Rigtige data fra KickoffAPI'; $('#notice').innerHTML=state.error?`<div class="error"><b>Der er et API-problem:</b><br>${esc(state.error)}<br><span class="small">Der bruges /fixtures?league=1&season=2026. Ingen fallback eller demodata.</span></div><br>`:''; if(state.loading){$('#view').innerHTML='<div class="empty">Henter live-data fra KickoffAPI…</div>'; return;} if(state.selected) return renderDetail(); const map={overview,matches,groups,teams,stadiums,favorites,settings}; $('#view').innerHTML=(map[state.view]||overview)();}
function matchCard(f){const id=fixtureId(f); const h=home(f), a=away(f); const fav=state.favorites.has(String(id)); return `<div class="card match" onclick="loadDetail(state.fixtures.find(x=>String(fixtureId(x))==='${id}'))"><div class="match-head"><span>${esc(get(f,'league.round')||get(f,'league.name')||'VM 2026')}</span><span class="status">${esc(status(f)||'Planlagt')}</span></div><div class="score-row"><div class="team"><img class="flag" src="${flag(h)}" onerror="this.style.display='none'">${esc(teamName(h))}</div><div class="score">${score(f)}</div><div class="team away">${esc(teamName(a))}<img class="flag" src="${flag(a)}" onerror="this.style.display='none'"></div></div><div class="match-actions"><span class="muted small">${dateText(f)}${venueOf(f).name?' · '+esc(venueOf(f).name):''}</span><div><button class="info-btn" onclick="event.stopPropagation();loadDetail(state.fixtures.find(x=>String(fixtureId(x))==='${id}'))">Info</button><button class="ghost" onclick="event.stopPropagation();toggleFav('${id}')">${fav?'★':'☆'}</button></div></div></div>`}
function toggleFav(id){state.favorites.has(String(id))?state.favorites.delete(String(id)):state.favorites.add(String(id)); localStorage.setItem('favorites', JSON.stringify([...state.favorites])); render();}
function overview(){const sorted=[...state.fixtures].sort((a,b)=>(dt(a)||0)-(dt(b)||0)); const live=sorted.filter(f=>!isFinished(f)&&status(f)&&status(f)!=='NS').slice(0,4); const next=sorted.filter(f=>(dt(f)||0)>new Date()).slice(0,6); const done=sorted.filter(isFinished).slice(-4).reverse(); return `<div class="grid"><div class="hero"><h3>VM 2026</h3><p class="muted">Lys mobilapp med rigtige VM 2026-data fra KickoffAPI: league=1 og season=2026.</p><div class="grid three"><div><b>${state.fixtures.length}</b><br><span class="muted small">kampe hentet</span></div><div><b>${state.teams.length}</b><br><span class="muted small">hold fundet</span></div><div><b>${state.standings.length}</b><br><span class="muted small">standing-rækker</span></div></div></div><div><div class="section-title">Live / igang</div><div class="grid two">${(live.length?live:next.slice(0,2)).map(matchCard).join('')||'<div class="card empty">Ingen kampe hentet</div>'}</div></div><div><div class="section-title">Næste kampe</div><div class="grid two">${next.map(matchCard).join('')||'<div class="card empty">Ingen kommende kampe</div>'}</div></div><div><div class="section-title">Seneste resultater</div><div class="grid two">${done.map(matchCard).join('')||'<div class="card empty">Ingen resultater endnu</div>'}</div></div></div>`}
function matches(){const grouped={}; [...state.fixtures].sort((a,b)=>(dt(a)||0)-(dt(b)||0)).forEach(f=>{const d=dt(f); const k=d?d.toLocaleDateString('da-DK',{weekday:'long',day:'numeric',month:'long'}):'Uden dato'; (grouped[k]??=[]).push(f)}); return Object.entries(grouped).map(([d,list])=>`<div class="section-title">${d}</div><div class="grid two">${list.map(matchCard).join('')}</div>`).join('')||'<div class="empty">Ingen kampe hentet fra /fixtures?league=1&season=2026.</div>'}
function groups(){let rows=[]; state.standings.forEach(g=>{if(Array.isArray(g.league?.standings)) g.league.standings.flat().forEach(r=>rows.push({...r,group:r.group||g.league?.round||''})); else if(Array.isArray(g)) rows.push(...g);}); if(!rows.length) return '<div class="card empty">Ingen stillinger hentet fra standings endnu.</div>'; const groups={}; rows.forEach(r=>(groups[r.group||'Gruppe']??=[]).push(r)); return Object.entries(groups).map(([g,list])=>`<div class="card pad"><h3>${esc(g)}</h3><table class="table"><tr><th>#</th><th>Hold</th><th>P</th><th>M</th><th>V</th><th>U</th><th>T</th><th>MF</th></tr>${list.map(r=>`<tr><td>${r.rank??''}</td><td><img class="team-logo" src="${flag(r.team)}" onerror="this.style.display='none'">${esc(teamName(r.team))}</td><td><b>${r.points??''}</b></td><td>${r.all?.played??''}</td><td>${r.all?.win??''}</td><td>${r.all?.draw??''}</td><td>${r.all?.lose??''}</td><td>${r.goalsDiff??''}</td></tr>`).join('')}</table></div>`).join('<br>')}
function teams(){return `<div class="grid three">${state.teams.map(t=>{const x=t.team||t;return `<div class="card pad"><img class="team-logo" src="${flag(x)}" onerror="this.style.display='none'"><b>${esc(teamName(x))}</b><br><span class="muted small">${esc(x.country||'')}</span></div>`}).join('')||'<div class="card empty">Ingen hold hentet.</div>'}</div>`}
function stadiums(){return `<div class="grid two">${state.venues.slice(0,80).map(v=>{v=v.venue||v;return `<div class="card pad">${v.image?`<img src="${esc(v.image)}" style="width:100%;height:140px;object-fit:cover;border-radius:16px;margin-bottom:12px" onerror="this.style.display='none'">`:''}<h3>${esc(v.name||'Stadion')}</h3><div class="muted">${esc(v.city||'')} ${v.capacity?'• '+Number(v.capacity).toLocaleString('da-DK')+' pladser':''}</div></div>`}).join('')||'<div class="card empty">Ingen stadions hentet.</div>'}</div>`}
function favorites(){const list=state.fixtures.filter(f=>state.favorites.has(String(fixtureId(f)))); return `<div class="grid two">${list.map(matchCard).join('')||'<div class="card empty">Ingen favoritter endnu.</div>'}</div>`}
function settings(){return `<div class="card pad"><h3>API</h3><p><b>Base URL:</b> ${BASE}/</p><p><b>Auth header:</b> x-api-key</p><p><b>VM 2026:</b> league=${WORLD_CUP_LEAGUE_ID}, season=${SEASON}</p><p class="muted">Ingen demodata og ingen fallback. Appen bruger kun <code>/fixtures</code>, <code>/fixtures/events?fixture=ID</code>, <code>/fixtures/lineups?fixture=ID</code> og <code>/fixtures/statistics?fixture=ID</code>.</p><button class="ghost" onclick="localStorage.clear();location.reload()">Ryd cache helt</button></div>`}
function renderDetail(){const s=state.selected, f=s.fixture, h=home(f), a=away(f); const tabs=[['fakta','Fakta'],['opstillinger','Opstillinger'],['statistik','Statistik'],['kampforlob','Kampforløb']]; $('#view').innerHTML=`<button class="ghost" onclick="state.selected=null;render()">← Tilbage</button><br><br><section class="hero"><div class="hero-main"><div class="team"><img class="flag" src="${flag(h)}" onerror="this.style.display='none'"><span>${esc(teamName(h))}</span></div><div><div class="muted small">${esc(get(f,'league.round')||'VM 2026')}</div><div class="muted small">${dateText(f)}</div><div class="score">${score(f)}</div><div class="status">${esc(status(f)||'')}</div></div><div class="team"><img class="flag" src="${flag(a)}" onerror="this.style.display='none'"><span>${esc(teamName(a))}</span></div></div><div class="tabs">${tabs.map(([id,label])=>`<button class="${state.detailTab===id?'active':''}" onclick="state.detailTab='${id}';render()">${label}</button>`).join('')}</div></section><br>${s.loading?'<div class="empty">Henter events, opstillinger og statistik…</div>':''}${s.errors?.length?`<div class="error small">Noget kampdata kunne ikke hentes:<br>${s.errors.map(esc).join('<br>')}</div><br>`:''}${detailContent()}`}
function detailContent(){const tab=state.detailTab, s=state.selected; if(tab==='opstillinger') return lineupsHtml(s.lineups||[], s.events||[]); if(tab==='statistik') return statsHtml(s.stats||[]); if(tab==='kampforlob') return eventsTimeline(s.events||[]); return faktaHtml(s.fixture,s.events||[],s.lineups||[],s.stats||[])}
function faktaHtml(f,events,lineups,stats){const h=home(f),a=away(f),v=venueOf(f); return `<div class="grid two"><div class="card pad"><h3>${esc(teamName(h))}</h3>${eventsFor(h,events)}</div><div class="card pad"><h3>${esc(teamName(a))}</h3>${eventsFor(a,events)}</div></div><br><div class="grid two"><div class="card pad"><h3>Kampinfo</h3><p><b>Status:</b> ${esc(status(f)||'Planlagt')}</p><p><b>Tid:</b> ${dateText(f)}</p><p><b>Stadion:</b> ${esc(v.name||'Ukendt')}${v.city?' · '+esc(v.city):''}</p><p><b>Halvleg:</b> ${esc((f.scoreHalfHome??'-')+' - '+(f.scoreHalfAway??'-'))}</p><p><b>Slut:</b> ${esc((f.scoreFullHome??'-')+' - '+(f.scoreFullAway??'-'))}</p>${f.scorePenaltyHome!=null||f.scorePenaltyAway!=null?`<p><b>Straffe:</b> ${esc((f.scorePenaltyHome??'-')+' - '+(f.scorePenaltyAway??'-'))}</p>`:''}</div><div class="card pad"><h3>Hurtigt overblik</h3>${statsHtml(stats,true)}${lineups?.length?`<p class="muted small">Opstillinger er hentet. Åbn fanen Opstillinger.</p>`:''}</div></div>`}
function sameTeam(a,b){return String(teamId(a)||teamName(a)).toLowerCase()===String(teamId(b)||teamName(b)).toLowerCase() || teamName(a)===teamName(b)}
function minute(e){const el=e.time?.elapsed??e.minute??e.elapsed??''; const ex=e.time?.extra??e.extra??''; return `${el}${ex?`+${ex}`:''}${el!==''?'\'':''}`}
function eventType(e){return String(e.type||e.detail||'')}
function eventsFor(team,events){const list=events.filter(e=>sameTeam(e.team,team)); return list.length?`<div class="event-list">${list.map(eventRow).join('')}</div>`:'<div class="muted">Ingen events registreret.</div>'}
function eventRow(e){const type=eventType(e); let icon='•', detail=e.detail||e.type||''; if(/goal/i.test(type)||/goal/i.test(detail)) icon='<span class="icon-goal">⚽</span>'; if(/card/i.test(type)||/card/i.test(detail)) icon=`<span class="icon-card ${/red/i.test(detail)?'icon-red':''}"></span>`; if(/subst/i.test(type)||/subst/i.test(detail)) icon='<span class="sub-in">↑</span>'; const player=e.player?.name||e.playerName||''; const assist=e.assist?.name||e.assistName||''; const main=/subst/i.test(type)?`<strong><span class="sub-in">↑ ${esc(assist||'Ind')}</span></strong><span class="sub-out">↓ ${esc(player||'Ud')}</span>`:`<strong>${esc(player||detail||type||'Event')}</strong>${assist?`<span class="muted small">Assist: ${esc(assist)}</span>`:''}`; return `<div class="event-row"><b>${esc(minute(e))}</b><span>${icon}</span><span class="event-main">${main}<span class="muted small">${esc(teamName(e.team)||'')}</span></span></div>`}
function eventsTimeline(events){const sorted=[...events].sort((a,b)=>(a.time?.elapsed||a.minute||0)-(b.time?.elapsed||b.minute||0)); return `<div class="card pad"><h3>Kampforløb</h3>${sorted.length?`<div class="event-list">${sorted.map(eventRow).join('')}</div>`:'<div class="muted">Ingen kamp-events hentet.</div>'}</div>`}
function playerEventBadges(player, events, lineupTeam){const name=player.name||player.player?.name||''; const team=lineupTeam?.team||lineupTeam; const ev=events.filter(e=>sameTeam(e.team,team)&&((e.player?.name||'')===name || (e.assist?.name||'')===name)); let icons=[]; if(ev.some(e=>/goal/i.test(eventType(e))||/goal/i.test(e.detail||''))) icons.push('⚽'); if(ev.some(e=>/yellow/i.test(e.detail||''))) icons.push('🟨'); if(ev.some(e=>/red/i.test(e.detail||''))) icons.push('🟥'); if(ev.some(e=>/subst/i.test(eventType(e)))) icons.push('🔁'); return icons.map(i=>`<span>${i}</span>`).join('')}
function lineupsHtml(lineups,events=[]){if(!lineups?.length) return '<div class="card empty">Ingen opstillinger hentet endnu.</div>'; const homeL=lineups[0], awayL=lineups[1]; return `<div class="card pad"><h3>Opstillinger</h3><div class="pitch-wrap"><div class="pitch-head"><span>${esc(teamName(homeL.team))} ${homeL.formation?`· ${esc(homeL.formation)}`:''}</span><span>${awayL?.formation?`${esc(awayL.formation)} · `:''}${esc(teamName(awayL?.team))}</span></div><div class="pitch"><div class="midline"></div><div class="circle"></div><div class="box-left"></div><div class="box-right"></div>${playersOnPitch(homeL,'home',events).join('')}${playersOnPitch(awayL,'away',events).join('')}</div></div><div class="bench"><div><b>Træner: ${esc(homeL.coach?.name||homeL.coach||'')}</b><ul>${(homeL.substitutes||[]).map(p=>`<li>${esc(p.player?.number||p.number||'')} ${esc(p.player?.name||p.name||'')}</li>`).join('')}</ul></div><div><b>Træner: ${esc(awayL?.coach?.name||awayL?.coach||'')}</b><ul>${(awayL?.substitutes||[]).map(p=>`<li>${esc(p.player?.number||p.number||'')} ${esc(p.player?.name||p.name||'')}</li>`).join('')}</ul></div></div></div>`}
function playersOnPitch(l,side,events=[]){if(!l) return []; const xi=l.startXI||l.start_xi||[]; const form=String(l.formation||'4-3-3').split('-').map(Number).filter(Boolean); const rows=[1,...(form.length?form:[4,3,3])]; const out=[]; let idx=0; rows.forEach((count,r)=>{for(let c=0;c<count;c++){const raw=xi[idx++]||{}; const p=raw.player||raw; const x=side==='home'?8+r*(38/(rows.length-1||1)):92-r*(38/(rows.length-1||1)); const y=((c+1)/(count+1))*86+7; const cls=r===0?(side==='home'?'keeper':'away-keeper'):(side==='home'?'home-shirt':'away-shirt'); const nm=p.name||''; out.push(`<div class="player" style="left:${x}%;top:${y}%"><div class="player-icons">${playerEventBadges(p,events,l)}</div><div class="shirt ${cls}">${esc(p.number||'')}</div><b>${esc(shortName(nm))}</b></div>`)}}); return out;}
function shortName(name){const parts=String(name).split(' ').filter(Boolean); return parts.length>2?parts.slice(-2).join(' '):name;}
function statsHtml(stats,compact=false){if(!stats?.length) return compact?'<div class="muted small">Ingen statistik hentet.</div>':'<div class="card empty">Ingen statistik hentet.</div>'; const a=stats[0], b=stats[1]; const list=(a.statistics||[]).map((s,i)=>[s.type,s.value,b?.statistics?.[i]?.value]); const html=`${list.map(([name,hv,av])=>statRow(name,hv,av)).join('')}`; return compact?html:`<div class="card pad"><h3>Kampstatistik</h3>${html}</div>`}
function num(v){if(v==null)return 0; return Number(String(v).replace('%',''))||0} function statRow(name,hv,av){const h=num(hv), a=num(av), tot=h+a||1; return `<div class="stat-row"><b>${esc(hv??'-')}</b><div><div class="small muted" style="text-align:center">${esc(name)}</div><div class="bar"><i style="width:${h/tot*100}%"></i><i style="width:${a/tot*100}%"></i></div></div><b style="text-align:right">${esc(av??'-')}</b></div>`}
$('#refreshBtn').onclick=()=>loadCore(true);
let deferredPrompt; window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false}); $('#installBtn').onclick=()=>deferredPrompt?.prompt();
if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js');
render(); loadCore();
